# Generated by Django 6.0.5 on 2026-05-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_rendezvous_statut'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.medecin'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='part_assurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='part_patient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('moov', 'Moov Money (Flooz)'), ('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('wave', 'Wave'), ('celtiis', 'Celtiis Cash'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement'), ('assurance', 'Assurance CNSS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('partiel', 'Partiel'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
