# Generated by Django 6.0.5 on 2026-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_remove_facture_montant_facture_facture_id_and_more'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin'),
        ),
    ]
