# Generated by Django 6.0.5 on 2026-05-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('cardiologue', 'Cardiologue'), ('generaliste', 'Généraliste'), ('dermatologue', 'Dermatologue'), ('gynecologue', 'Gynécologue'), ('neurologue', 'Neurologue'), ('ophtalmologue', 'Ophtalmologue'), ('pediatre', 'Pédiatre'), ('radiologue', 'Radiologue')], max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cabinet', models.CharField(blank=True, max_length=200)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médecin',
                'ordering': ['nom'],
            },
        ),
    ]
