# Generated by Django 5.2.8 on 2026-07-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0001_initial'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='hopitaux.hopital'),
        ),
    ]
