# Generated by Django 6.0.5 on 2026-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date', '-heure']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='type_consultation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
