# Generated by Django 6.0.5 on 2026-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_options_and_more'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin'),
        ),
    ]
