# Generated by Django 5.2.8 on 2026-07-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopitaux', '0001_initial'),
        ('patients', '0002_alter_patient_allergies_alter_patient_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hopitaux.hopital'),
        ),
    ]
