# Generated by Django 6.0.5 on 2026-05-11 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_rendezvous_statut'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_evenement', models.CharField(choices=[('rendez_vous', 'Rendez-Vous'), ('consultation', 'Consultation'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='rendez_vous', max_length=20)),
                ('couleur', models.CharField(choices=[('blue', '#2563EB'), ('green', '#16A34A'), ('orange', '#D97706'), ('red', '#DC2626'), ('purple', '#9333EA')], default='blue', max_length=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.medecin')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
