# Generated by Django 6.0.5 on 2026-05-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('reporte', 'Reporté'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20),
        ),
    ]
