# Generated by Django 6.0.5 on 2026-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_rendezvous_statut'),
        ('calendrier', '0002_alter_evenement_medecin'),
        ('consultations', '0003_alter_consultation_medecin'),
        ('dossiers_medicaux', '0003_alter_dossiermedical_medecin_referent'),
        ('facturation', '0003_alter_facture_medecin'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin'),
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
    ]
