# Generated by Django 6.0.5 on 2026-05-11 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='medecin',
        ),
        migrations.AddField(
            model_name='conversation',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type_contact',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('equipe', 'Équipe'), ('vendor', 'Vendeur')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
