# Generated by Django 6.0.5 on 2026-05-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(choices=[('sang', 'Analyse de sang'), ('radiographie', 'Radiographie'), ('covid', 'Test COVID-19'), ('urine', "Analyse d'urine"), ('autre', 'Autre')], max_length=50)),
                ('laboratoire', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('disponible', 'Disponible'), ('critique', 'Critique')], default='en_attente', max_length=20)),
                ('resultat', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='analyses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
