# Generated by Django 6.0.5 on 2026-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='medecin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medecins.medecin'),
            preserve_default=False,
        ),
    ]
