# Generated by Django 6.0.5 on 2026-05-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_alter_analyse_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='medecin',
        ),
    ]
