# Generated by Django 6.0.5 on 2026-05-07 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.TextField(blank=True)),
                ('traitements_en_cours', models.TextField(blank=True)),
                ('notes_medicales', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('duree', models.CharField(max_length=100)),
                ('date_prescription', models.DateField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.consultation')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dossiers_medicaux.dossiermedical')),
            ],
        ),
    ]
