# Generated by Django 6.0.5 on 2026-05-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_rendezvous_statut'),
        ('dossiers_medicaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossiermedical',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='medecin_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.medecin'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='nb_documents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='statut',
            field=models.CharField(choices=[('valide', 'Validé'), ('en_attente', 'En attente'), ('urgent', 'Urgent')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('ordonnance', 'Ordonnance'), ('analyse', "Résultat d'analyse"), ('imagerie', 'Imagerie (Radio/IRM)'), ('compte_rendu', 'Compte-rendu'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers_medicaux.dossiermedical')),
            ],
        ),
    ]
