# Generated by Django 6.0.5 on 2026-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers_medicaux', '0002_alter_dossiermedical_options_and_more'),
        ('medecins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='medecin_referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.medecin'),
        ),
    ]
